//! PRD #77 Decision 30 — auto-generate a Markdown doc next to every
//! `#[spec]`-annotated test under
//! `.dot-agent-deck/recordings/<test-fn-name>/test.md`.
//!
//! `.dot-agent-deck/` is developer-machine state, gitignored, and
//! regenerated by `cargo xtask docs --tests` (plus the L2 harness's
//! on-record / on-failure hook). The Scenario doc comment in the test
//! source is the authoritative external-reader surface; the `.md` is
//! a local rendered view that pairs with the cast under the same
//! per-test directory.
//!
//! The generator is deterministic: running it twice on unchanged
//! inputs produces byte-identical output. M4.3 simplification —
//! linkage-check rule 7 no longer byte-diffs the on-disk `.md`
//! against a fresh regen (the on-disk file may not exist for a fresh
//! clone). Rule 7 now asserts (a) every `#[spec]` test has a
//! `/// Scenario:` doc comment with a body and (b) `generate_all`
//! succeeds against the current source + catalog.
//!
//! Inputs:
//!   - The catalog under `prds/done/77-tui-testing-harness.md` (parsed
//!     for entry headlines + body fields).
//!   - Every `#[spec("…")]`-annotated test fn under `tests/` AND `src/`
//!     (parsed via `syn` for fn name, doc comments, and statement-level
//!     method calls on the harness builder / handle). PRD #83 added
//!     per-tab-selection unit tests in `src/tab.rs`, so the library
//!     crate is walked too.
//!
//! Output:
//!   - One `.md` per `#[spec]` test, written to
//!     `.dot-agent-deck/recordings/<test-fn-name>/test.md`.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use regex::Regex;
use syn::spanned::Spanned;

/// Single source of truth for the catalog-pointer line in every
/// generated `.md`. Reviewer Nit 2 — was duplicated literally in
/// the renderer; pulled here so a future location change doesn't
/// fork.
const CATALOG_REF: &str = "PRD #77 `## Test Case Catalog`";

// ---------------------------------------------------------------------------
// Public surface
// ---------------------------------------------------------------------------

/// Configuration the binary + harness pass in: where to read from
/// and where to write to. Absolute paths so cwd doesn't matter.
#[derive(Debug, Clone)]
pub struct DocsConfig {
    pub workspace_root: PathBuf,
    pub prd_path: PathBuf,
    pub tests_dir: PathBuf,
    /// PRD #83: `#[spec]` tests also live in the library crate
    /// (e.g. `src/tab.rs` unit/integration tests), so the generator
    /// walks `src/` in addition to `tests/`.
    pub src_dir: PathBuf,
    /// `.dot-agent-deck/recordings` — parent of every per-test
    /// subdirectory written by the generator (M4.3 flattened layout).
    pub recordings_root: PathBuf,
}

impl DocsConfig {
    /// Build the canonical config rooted at `workspace_root`.
    pub fn from_workspace(workspace_root: impl Into<PathBuf>) -> Self {
        let workspace_root = workspace_root.into();
        Self {
            // PRD #77 archived to prds/done/ (commit 637eb37).
            prd_path: workspace_root.join("prds/done/77-tui-testing-harness.md"),
            tests_dir: workspace_root.join("tests"),
            src_dir: workspace_root.join("src"),
            recordings_root: workspace_root.join(".dot-agent-deck").join("recordings"),
            workspace_root,
        }
    }
}

/// One generated doc — its destination path and the byte contents
/// the linkage-check rule 7 diff compares against.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedDoc {
    pub spec_id: String,
    pub fn_name: String,
    pub source_path: PathBuf,
    pub output_path: PathBuf,
    pub content: String,
}

/// A `#[spec("…")]` test found in `tests/`. Public so the harness
/// can pass a single spec id straight into [`generate_for_spec`].
#[derive(Debug, Clone)]
pub struct DiscoveredTest {
    pub spec_id: String,
    pub fn_name: String,
    pub source_path: PathBuf,
    pub scenario: Option<String>,
    pub steps: Vec<String>,
}

/// Generate the `.md` content for every `#[spec]` test under
/// `tests/`. Sorted deterministically by `spec_id` so the output
/// order is stable.
pub fn generate_all(config: &DocsConfig) -> Result<Vec<GeneratedDoc>, String> {
    let catalog = parse_catalog(&config.prd_path)?;
    let mut tests = discover_tests(&config.tests_dir)?;
    // PRD #83: library-crate `#[spec]` tests (e.g. `src/tab.rs`) are
    // discovered too.
    tests.extend(discover_tests(&config.src_dir)?);
    tests.sort_by(|a, b| a.spec_id.cmp(&b.spec_id));
    let mut out: Vec<GeneratedDoc> = Vec::with_capacity(tests.len());
    for t in &tests {
        let entry = catalog.get(&t.spec_id).ok_or_else(|| {
            format!(
                "test `{}` in {} carries #[spec({:?})] which is not in the catalog",
                t.fn_name,
                t.source_path.display(),
                t.spec_id,
            )
        })?;
        let scenario = t.scenario.as_deref().unwrap_or("").trim();
        if scenario.is_empty() {
            return Err(format!(
                "test `{}` in {} is missing a `/// Scenario:` doc comment with a body \
                 (PRD #77 Decision 30 / linkage-check rule 7)",
                t.fn_name,
                t.source_path.display(),
            ));
        }
        let output_path = resolve_output_path(&config.recordings_root, &t.fn_name);
        let content = render_markdown(t, entry, scenario);
        out.push(GeneratedDoc {
            spec_id: t.spec_id.clone(),
            fn_name: t.fn_name.clone(),
            source_path: t.source_path.clone(),
            output_path,
            content,
        });
    }
    Ok(out)
}

/// Generate exactly one doc, by spec id. Used by the harness's
/// regen-on-record hook so we don't re-parse all tests for one
/// captured run. Returns `Ok(None)` when the spec id has no
/// matching test (forgiving: harness doesn't want to noisily fail
/// during a test run).
pub fn generate_for_spec(
    config: &DocsConfig,
    spec_id: &str,
) -> Result<Option<GeneratedDoc>, String> {
    let all = generate_all(config)?;
    Ok(all.into_iter().find(|d| d.spec_id == spec_id))
}

/// Write every generated doc to disk under its `output_path`.
/// Creates parent dirs as needed. M4.1 auditor S3: each file is
/// written via a `NamedTempFile::new_in(parent)` followed by
/// `persist(dst)`, so concurrent invocations (e.g. one
/// `cargo xtask docs --tests` racing the harness's regen-on-record
/// hook) cannot race-corrupt a `.md` mid-write — the rename is
/// atomic on Unix because the tempfile lives in the same parent
/// directory as the destination.
pub fn write_all(generated: &[GeneratedDoc]) -> Result<Vec<PathBuf>, String> {
    use std::io::Write;
    let mut paths = Vec::with_capacity(generated.len());
    for g in generated {
        let parent = g.output_path.parent().ok_or_else(|| {
            format!(
                "output path has no parent directory: {}",
                g.output_path.display()
            )
        })?;
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("create parent dir {}: {e}", parent.display()))?;
        let mut tmp = tempfile::Builder::new()
            .prefix(".xtask-docs-")
            .suffix(".md.tmp")
            .tempfile_in(parent)
            .map_err(|e| format!("create tempfile in {}: {e}", parent.display()))?;
        tmp.write_all(g.content.as_bytes())
            .map_err(|e| format!("write tempfile for {}: {e}", g.output_path.display()))?;
        tmp.as_file()
            .sync_all()
            .map_err(|e| format!("sync tempfile for {}: {e}", g.output_path.display()))?;
        tmp.persist(&g.output_path)
            .map_err(|e| format!("rename into place {}: {e}", g.output_path.display()))?;
        paths.push(g.output_path.clone());
    }
    Ok(paths)
}

/// M4.3 rule 7 entry point — exercises the generator end-to-end as
/// a smoke test and returns `Ok(())` when every `#[spec]` test under
/// `tests/` carries a `/// Scenario:` doc comment with a body and
/// the markdown for each test renders without error.
///
/// Replaces the prior byte-identity diff against on-disk `.md`
/// files: with `.dot-agent-deck/` now gitignored, a fresh clone has
/// no on-disk `.md` to diff against. The Scenario doc comment +
/// generator-success pair is what the convention actually requires.
pub fn check_rule_7(config: &DocsConfig) -> Result<(), String> {
    // `generate_all` already returns `Err` when a #[spec] test is
    // missing its `/// Scenario:` doc comment OR when the generator
    // hits a malformed test source. Discard the result — we only
    // care that it succeeds.
    generate_all(config).map(|_| ())
}

// ---------------------------------------------------------------------------
// Catalog parsing
// ---------------------------------------------------------------------------

/// Single catalog entry parsed from the PRD's `## Test Case Catalog`
/// block. The fields mirror the bullets every entry carries.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CatalogEntry {
    pub id: String,
    pub headline: String,
    pub layer: Option<String>,
    pub agent: Option<String>,
    pub asserts: Option<String>,
    pub does_not_assert: Option<String>,
    pub platform_coverage: Option<String>,
    pub cost_note: Option<String>,
}

/// Parse every `##### <id> — <headline>` heading + its bullet lines
/// out of the PRD's `## Test Case Catalog` section. Returns a map
/// keyed by catalog id.
pub fn parse_catalog(prd_path: &Path) -> Result<BTreeMap<String, CatalogEntry>, String> {
    // M4.1 auditor S1: refuse a symlinked PRD path with a redacted,
    // specific error — matches the M3.1 auditor S3 stance on
    // symlinked credential / fixture sources.
    let meta = std::fs::symlink_metadata(prd_path)
        .map_err(|e| format!("stat {}: {e}", prd_path.display()))?;
    let file_type = meta.file_type();
    if file_type.is_symlink() {
        return Err(format!(
            "expected real file at {}, found symlink",
            prd_path.display()
        ));
    }
    if !file_type.is_file() {
        return Err(format!(
            "expected real file at {}, found {file_type:?}",
            prd_path.display()
        ));
    }
    let text = std::fs::read_to_string(prd_path)
        .map_err(|e| format!("read {}: {e}", prd_path.display()))?;
    let header_re = Regex::new(r"^#####\s+([a-z][a-z0-9-]*/[a-z][a-z0-9-]*/\d{3})\s*[—-]\s*(.+)$")
        .expect("catalog header regex compiles");
    let bullet_re =
        Regex::new(r"^- \*\*([^*]+):\*\*\s*(.+)$").expect("catalog bullet regex compiles");

    let mut out: BTreeMap<String, CatalogEntry> = BTreeMap::new();
    let mut in_catalog = false;
    let mut current: Option<CatalogEntry> = None;
    for line in text.lines() {
        if line.starts_with("## ") {
            // Section boundary — flush whatever entry is open before
            // we change in/out of catalog.
            if let Some(entry) = current.take() {
                out.insert(entry.id.clone(), entry);
            }
            in_catalog = line.starts_with("## Test Case Catalog");
            continue;
        }
        if !in_catalog {
            continue;
        }
        if let Some(caps) = header_re.captures(line) {
            if let Some(entry) = current.take() {
                out.insert(entry.id.clone(), entry);
            }
            current = Some(CatalogEntry {
                id: caps.get(1).unwrap().as_str().to_string(),
                headline: caps.get(2).unwrap().as_str().trim().to_string(),
                layer: None,
                agent: None,
                asserts: None,
                does_not_assert: None,
                platform_coverage: None,
                cost_note: None,
            });
            continue;
        }
        if let Some(caps) = bullet_re.captures(line)
            && let Some(entry) = current.as_mut()
        {
            let key = caps.get(1).unwrap().as_str().trim().to_lowercase();
            let value = caps.get(2).unwrap().as_str().trim().to_string();
            match key.as_str() {
                "layer" => entry.layer = Some(value),
                "agent" => entry.agent = Some(value),
                "asserts" => entry.asserts = Some(value),
                "does not assert" => entry.does_not_assert = Some(value),
                "platform coverage" => entry.platform_coverage = Some(value),
                "cost note" => entry.cost_note = Some(value),
                _ => {}
            }
        }
    }
    if let Some(entry) = current.take() {
        out.insert(entry.id.clone(), entry);
    }
    Ok(out)
}

// ---------------------------------------------------------------------------
// Test source discovery
// ---------------------------------------------------------------------------

/// Walk `dir` recursively and return every `#[spec("…")]`-annotated
/// test fn we find, sorted by spec id for determinism. Used for both
/// `tests/` and (PRD #83) the library crate's `src/`.
pub fn discover_tests(dir: &Path) -> Result<Vec<DiscoveredTest>, String> {
    let mut files: Vec<PathBuf> = Vec::new();
    collect_rs_files(dir, &mut files)?;
    files.sort();
    let mut out: Vec<DiscoveredTest> = Vec::new();
    for path in files {
        let source = match std::fs::read_to_string(&path) {
            Ok(s) => s,
            Err(e) => {
                return Err(format!("read test source {}: {e}", path.display()));
            }
        };
        // PRD #83: only syn-parse files that actually carry a `#[spec(`
        // annotation. Walking `src/` would otherwise parse the entire
        // library crate every run and turn any single file syn can't
        // handle into a generator failure — neither is wanted when the
        // only spec-bearing source files are a handful.
        if !source.contains("#[spec(") {
            continue;
        }
        let parsed = match syn::parse_file(&source) {
            Ok(p) => p,
            Err(e) => {
                return Err(format!("parse test source {}: {e}", path.display()));
            }
        };
        // M4.6 P2: walk both top-level items AND items nested inside
        // inline `mod` blocks. A `#[spec]` test placed inside
        // `#[cfg(test)] mod foo { ... }` was previously silently
        // dropped, which let linkage-check rule 7 pass against tests
        // the generator never saw.
        collect_spec_tests_from_items(&parsed.items, &path, &mut out);
    }
    Ok(out)
}

/// Recurse into `items`, pushing every `#[spec]`-annotated fn to
/// `out`. Items inside inline `Item::Mod { content: Some(_) }` are
/// walked the same way. External `mod foo;` declarations (no inline
/// content) are skipped — resolving them would require a file
/// lookup that's out of scope for the test-file walker (PRD #77 M4.6
/// P2).
fn collect_spec_tests_from_items(items: &[syn::Item], path: &Path, out: &mut Vec<DiscoveredTest>) {
    for item in items {
        match item {
            syn::Item::Fn(item_fn) => {
                if let Some(spec_id) = read_spec_attr(&item_fn.attrs) {
                    let fn_name = item_fn.sig.ident.to_string();
                    let scenario = read_scenario_doc(&item_fn.attrs);
                    let steps = extract_steps_from_body(&item_fn.block);
                    out.push(DiscoveredTest {
                        spec_id,
                        fn_name,
                        source_path: path.to_path_buf(),
                        scenario,
                        steps,
                    });
                }
            }
            syn::Item::Mod(item_mod) => {
                if let Some((_, nested_items)) = &item_mod.content {
                    collect_spec_tests_from_items(nested_items, path, out);
                }
            }
            _ => {}
        }
    }
}

fn collect_rs_files(dir: &Path, acc: &mut Vec<PathBuf>) -> Result<(), String> {
    let rd = match std::fs::read_dir(dir) {
        Ok(rd) => rd,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(e) => return Err(format!("read_dir {}: {e}", dir.display())),
    };
    for entry in rd {
        let entry = entry.map_err(|e| format!("read_dir entry under {}: {e}", dir.display()))?;
        let p = entry.path();
        // M4.1 auditor S2: refuse symlinks LOUDLY under `tests/` —
        // matches the M3 copy_dir_recursively stance. A fixture or
        // test should never be a symlink; loud refusal catches
        // accidents instead of silently skipping them.
        let meta = std::fs::symlink_metadata(&p)
            .map_err(|e| format!("symlink_metadata {}: {e}", p.display()))?;
        let ft = meta.file_type();
        if ft.is_symlink() {
            return Err(format!(
                "refusing to follow symlink under tests/: {}",
                p.display()
            ));
        }
        if ft.is_dir() {
            collect_rs_files(&p, acc)?;
        } else if ft.is_file() && p.extension().and_then(|e| e.to_str()) == Some("rs") {
            acc.push(p);
        }
    }
    Ok(())
}

fn read_spec_attr(attrs: &[syn::Attribute]) -> Option<String> {
    for attr in attrs {
        if !attr.path().is_ident("spec") {
            continue;
        }
        // #[spec("…")] — the inner token stream is one string literal.
        let parsed: Result<syn::LitStr, _> = attr.parse_args();
        if let Ok(lit) = parsed {
            return Some(lit.value());
        }
    }
    None
}

/// Scan the function's doc attributes for the first `/// Scenario:`
/// line and capture everything from there until a non-doc-comment
/// boundary. M4.1 reviewer S2: blank doc lines inside the Scenario
/// become paragraph breaks (`\n\n`) in the rendered .md, so the
/// extractor no longer silently truncates multi-paragraph
/// Scenarios. M4.1 reviewer Nit 3: the regex now matches the
/// singular form only — `/// Scenarios:` (plural) does NOT trigger,
/// because the author asked for "Scenario" exactly.
fn read_scenario_doc(attrs: &[syn::Attribute]) -> Option<String> {
    let lines: Vec<String> = attrs
        .iter()
        .filter(|a| a.path().is_ident("doc"))
        .filter_map(|a| {
            let mv: syn::MetaNameValue = a.meta.require_name_value().ok().cloned()?;
            if let syn::Expr::Lit(syn::ExprLit {
                lit: syn::Lit::Str(s),
                ..
            }) = mv.value
            {
                Some(s.value())
            } else {
                None
            }
        })
        .collect();
    extract_scenario_from_doc_lines(&lines)
}

/// Pure helper extracted for unit testing: takes the doc-comment
/// lines (already stripped of `///`) and returns the Scenario body
/// with blank-line-driven paragraph breaks preserved as `\n\n`.
fn extract_scenario_from_doc_lines(lines: &[String]) -> Option<String> {
    // Match exactly the singular `scenario` token; the negative
    // lookahead pattern Rust's regex crate doesn't support, so we
    // assert the following char (after `scenario`) is NOT another
    // word char by checking word-end with a colon or whitespace.
    // The pattern: case-insensitive `scenario` followed by `:` or
    // whitespace or end-of-string — NOT `s` / further letters.
    let scenario_marker = Regex::new(r"(?i)^\s*scenario(?:\s*:|\s+|\s*$)").expect("scenario regex");
    let start = lines
        .iter()
        .position(|line| scenario_marker.is_match(line))?;
    // Strip the `Scenario:` prefix from the first line — leaves
    // whatever inline content followed.
    let first_line = scenario_marker
        .replace(&lines[start], "")
        .trim()
        .to_string();

    let mut paragraphs: Vec<Vec<String>> = Vec::new();
    let mut current: Vec<String> = Vec::new();
    if !first_line.is_empty() {
        current.push(first_line);
    }
    for line in lines.iter().skip(start + 1) {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            if !current.is_empty() {
                paragraphs.push(std::mem::take(&mut current));
            }
            continue;
        }
        // A second `Scenario:` marker terminates this scenario —
        // one Scenario per test.
        if scenario_marker.is_match(line) {
            break;
        }
        current.push(trimmed.to_string());
    }
    if !current.is_empty() {
        paragraphs.push(current);
    }
    if paragraphs.is_empty() {
        return None;
    }
    Some(
        paragraphs
            .into_iter()
            .map(|p| p.join(" "))
            .collect::<Vec<_>>()
            .join("\n\n"),
    )
}

// ---------------------------------------------------------------------------
// Step extraction
// ---------------------------------------------------------------------------

/// Walk top-level statements in the test fn body and emit one plain
/// English step per recognized harness call. Closures, loops, match
/// arms, and unknown methods all degrade to a `Call: …(...)` raw
/// fallback rather than panicking (Decision 30 / task spec).
fn extract_steps_from_body(block: &syn::Block) -> Vec<String> {
    let mut steps: Vec<String> = Vec::new();
    for stmt in &block.stmts {
        collect_steps_from_stmt(stmt, &mut steps);
    }
    steps
}

fn collect_steps_from_stmt(stmt: &syn::Stmt, steps: &mut Vec<String>) {
    let expr_to_walk: &syn::Expr = match stmt {
        syn::Stmt::Local(local) => match &local.init {
            Some(init) => &init.expr,
            None => return,
        },
        syn::Stmt::Expr(e, _) => e,
        syn::Stmt::Macro(m) => {
            if let Some(step) = step_for_macro(&m.mac) {
                steps.push(step);
            }
            return;
        }
        _ => return,
    };
    walk_expr_for_steps(expr_to_walk, steps);
}

fn walk_expr_for_steps(expr: &syn::Expr, steps: &mut Vec<String>) {
    // M4.1 reviewer S1: a call records ONE step for the outer
    // invocation. We do NOT recurse into its arguments — the recipe
    // is "what the test did," not "every helper invoked." Method
    // chains still walk the receiver because each link in the
    // chain is itself a test action (`.with_imported_…()`
    // ‑> `.with_continue_session(…)` etc.).
    match expr {
        syn::Expr::MethodCall(call) => {
            walk_expr_for_steps(&call.receiver, steps);
            let name = call.method.to_string();
            let args = call.args.iter().map(display_expr).collect::<Vec<_>>();
            if let Some(step) = step_for_method(&name, &args) {
                steps.push(step);
            }
        }
        // Free-standing call like `write_hook_line(socket, payload)`.
        syn::Expr::Call(call) => {
            if let syn::Expr::Path(p) = &*call.func
                && let Some(name) = p.path.segments.last().map(|s| s.ident.to_string())
            {
                let args = call.args.iter().map(display_expr).collect::<Vec<_>>();
                if let Some(step) = step_for_free_call(&name, &args) {
                    steps.push(step);
                }
            }
        }
        syn::Expr::Macro(m) => {
            if let Some(step) = step_for_macro(&m.mac) {
                steps.push(step);
            }
        }
        // `let x = expr?;` — walk through the `Try` / unary wrappers.
        syn::Expr::Try(t) => walk_expr_for_steps(&t.expr, steps),
        syn::Expr::Unary(u) => walk_expr_for_steps(&u.expr, steps),
        syn::Expr::Reference(r) => walk_expr_for_steps(&r.expr, steps),
        syn::Expr::Group(g) => walk_expr_for_steps(&g.expr, steps),
        syn::Expr::Paren(p) => walk_expr_for_steps(&p.expr, steps),
        _ => {}
    }
}

/// Harness method-name → step-template map. Decision 30 / task spec.
/// Keep entries short and add new harness methods one line at a
/// time. Unknown methods fall back to `Call: <name>(...)`.
fn step_for_method(name: &str, args: &[String]) -> Option<String> {
    let s = match name {
        "launch_with_fixture" => format!("Launch the deck with fixture {}", arg_or(args, 0)),
        "try_launch_with_fixture" => format!(
            "Launch the deck with fixture {} (fallible variant)",
            arg_or(args, 0)
        ),
        "wait_for_string" => format!("Wait for {} to appear on screen", arg_or(args, 0)),
        "wait_for_strings_in_order" => format!(
            "Wait for {} to appear in order in the rolling byte history",
            arg_or(args, 0)
        ),
        "wait_until_quiescent" => "Wait until the deck stops emitting output".to_string(),
        "with_imported_claude_credentials" => {
            "Import Claude credentials into the test HOME".to_string()
        }
        "with_imported_opencode_credentials" => {
            "Import OpenCode credentials into the test HOME".to_string()
        }
        "with_continue_session" => format!(
            "Stage a saved session {} running {}",
            arg_or(args, 0),
            arg_or(args, 1)
        ),
        "with_env" => format!("Override env {}={}", arg_or(args, 0), arg_or(args, 1)),
        "with_pty_size" => format!("Set the PTY to {}×{}", arg_or(args, 0), arg_or(args, 1)),
        "resize" => format!("Resize the PTY to {}×{}", arg_or(args, 0), arg_or(args, 1)),
        // Plumbing — no plain-English step. M4.1 reviewer S1
        // extends the skip list with the common language-level
        // method-call noise (`.expect`, `.unwrap`, `.to_string`,
        // `.into`, `.as_ref`, `.clone`) and the test-data-builder
        // helpers used by the L1 test (`rendered_height` is a
        // value lookup on the density enum).
        "builder" | "hook_socket_path" | "attach_socket_path" | "snapshot_grid" | "expect"
        | "unwrap" | "to_string" | "into" | "as_ref" | "as_str" | "as_path" | "clone"
        | "to_owned" | "rendered_height" => {
            return None;
        }
        _ => format!("Call: {name}({})", args.join(", ")),
    };
    Some(s)
}

fn step_for_free_call(name: &str, args: &[String]) -> Option<String> {
    // Skip language-level helpers and harness-entry plumbing that
    // are structural noise (Some/None/Ok/Err constructors,
    // TuiDeck::builder() that just starts the builder chain, etc.).
    // M4.1 reviewer S1: also skip the L1 test-data builders + lib
    // helpers (`resolve_palette`, `working_session_fixture`,
    // `buffer_to_text`) that appear in `tests/render_dashboard.rs`
    // and aren't test actions.
    if matches!(
        name,
        "Some"
            | "None"
            | "Ok"
            | "Err"
            | "String"
            | "Vec"
            | "PathBuf"
            | "Default"
            | "format"
            | "builder"
            | "working_session_fixture"
            | "buffer_to_text"
            // M4.1 reviewer S1 follow-on: `Utc::now()` and similar
            // clock/value lookups appear inline in test fixtures and
            // are not test actions — skip them so the Steps section
            // stays focused on what the test DID.
            | "now"
            | "from"
            | "from_str"
            | "new"
            | "default"
    ) {
        return None;
    }
    let s = match name {
        "write_hook_line" => {
            // Args: socket, payload. The payload is the
            // interesting one; the socket comes from the harness.
            format!("Write {} to the hook socket", arg_or(args, 1))
        }
        "render_card_to_buffer" => {
            "Render the session card into a `ratatui::TestBackend` buffer".to_string()
        }
        // M4.1 reviewer S1: `launch_with_fixture` can appear as a
        // free-function call (UFCS / static-method form) too. Mirror
        // the method-form step so both paths produce the same text.
        "launch_with_fixture" => format!("Launch the deck with fixture {}", arg_or(args, 0)),
        "try_launch_with_fixture" => format!(
            "Launch the deck with fixture {} (fallible variant)",
            arg_or(args, 0)
        ),
        // Decision 30 fallback: any other free call surfaces as a
        // raw `Call: name(...)` line so the author can see what was
        // recognized — and so adding a new harness function is
        // visible even before its step template lands in the map.
        other => format!("Call: {other}({})", args.join(", ")),
    };
    Some(s)
}

fn step_for_macro(mac: &syn::Macro) -> Option<String> {
    let name = mac.path.segments.last()?.ident.to_string();
    let body = tokens_to_arg_list(mac.tokens.clone());
    match name.as_str() {
        "skip_unless" => {
            // The arg is a check_*_available() call — match by name
            // so unknown checks fall back to the generic form.
            let arg0 = body.first().map(String::as_str).unwrap_or("");
            if arg0.contains("check_claude_available") {
                Some("Skip unless Claude Code CLI is available".to_string())
            } else if arg0.contains("check_opencode_available") {
                Some("Skip unless OpenCode CLI is available".to_string())
            } else {
                Some(format!("Skip unless {arg0}"))
            }
        }
        "assert_snapshot" => Some("Snapshot the rendered buffer (insta)".to_string()),
        _ => None,
    }
}

fn arg_or(args: &[String], i: usize) -> String {
    args.get(i).cloned().unwrap_or_else(|| "?".to_string())
}

/// Render a syn::Expr argument as a compact display string. Strips
/// outer references / parens and unwraps string literals so the
/// rendered step reads naturally.
fn display_expr(expr: &syn::Expr) -> String {
    match expr {
        syn::Expr::Lit(syn::ExprLit {
            lit: syn::Lit::Str(s),
            ..
        }) => inline_code(&s.value()),
        syn::Expr::Lit(syn::ExprLit { lit, .. }) => inline_code(&lit_to_string(lit)),
        syn::Expr::Path(p) => {
            // Render the path's last segment to keep it short.
            p.path
                .segments
                .last()
                .map(|s| inline_code(&s.ident.to_string()))
                .unwrap_or_else(|| inline_code("_"))
        }
        syn::Expr::Reference(r) => display_expr(&r.expr),
        syn::Expr::Paren(p) => display_expr(&p.expr),
        syn::Expr::Group(g) => display_expr(&g.expr),
        syn::Expr::Array(a) => {
            // M4.6: render array literals (e.g.
            // `&["Thinking", "Working"]` passed to
            // `wait_for_strings_in_order`) as a compact bracketed
            // list rather than the generic `…` placeholder, so the
            // generated Steps line carries the actual sequence.
            let rendered = a
                .elems
                .iter()
                .map(display_expr)
                .collect::<Vec<_>>()
                .join(", ");
            format!("[{rendered}]")
        }
        syn::Expr::MethodCall(m) => {
            // E.g. `&agent_command` or `cmd.as_str()` — show the
            // method name.
            inline_code(&format!("{}(…)", m.method))
        }
        syn::Expr::Macro(m) => {
            // E.g. format!("…") — show the macro path's last segment.
            m.mac
                .path
                .segments
                .last()
                .map(|s| inline_code(&format!("{}!(…)", s.ident)))
                .unwrap_or_else(|| inline_code("_!(…)"))
        }
        other => {
            let span = other.span();
            // Fallback to a quote-of-tokens render via the source-text
            // helper. `quote::ToTokens` would be one path; use the
            // simpler `format!` against the span's source representation
            // — but that requires source map access. For safety, fall
            // back to a placeholder.
            let _ = span;
            "`…`".to_string()
        }
    }
}

fn lit_to_string(lit: &syn::Lit) -> String {
    match lit {
        syn::Lit::Str(s) => s.value(),
        syn::Lit::Int(i) => i.base10_digits().to_string(),
        syn::Lit::Bool(b) => b.value.to_string(),
        syn::Lit::Char(c) => c.value().to_string(),
        _ => "_".to_string(),
    }
}

/// Wrap `value` as a CommonMark inline-code span, picking a
/// backtick run length that's longer than the longest run of
/// backticks already present in `value` (M4.1 auditor S6). For
/// the common case (no backticks) the result is the familiar
/// single-backtick form `` `value` ``.
fn inline_code(value: &str) -> String {
    let longest_run = value
        .as_bytes()
        .iter()
        .fold((0usize, 0usize), |(longest, current), &b| {
            if b == b'`' {
                let c = current + 1;
                (longest.max(c), c)
            } else {
                (longest, 0)
            }
        })
        .0;
    let fence = "`".repeat(longest_run + 1);
    // CommonMark requires a single space of padding when the code
    // span starts or ends with a backtick; cheap to always add for
    // multi-backtick fences.
    if longest_run > 0 {
        format!("{fence} {value} {fence}")
    } else {
        format!("{fence}{value}{fence}")
    }
}

/// Sanitize Scenario doc-comment content before it lands in the
/// generated `.md`. M4.1 auditor S5: a hostile contributor could
/// otherwise smuggle:
/// - Raw HTML (`<script>…</script>`, `<img onerror=…>`) — GitHub's
///   markdown renderer strips most of it but some inline HTML
///   passes through into PR review surfaces.
/// - Markdown link syntax (`[click](javascript:…)`, `[exfil](https://…)`).
/// - Image syntax (`![x](https://…)`) which auto-fetches at render
///   time, leaking IP / UA.
///
/// This pass:
/// - HTML-escapes `<` and `>`.
/// - Escapes `[` and `]` so link/image syntax appears as literal
///   text (the author can put real links after the generated
///   block; the regenerated content stays sanitized).
/// - Leaves backticks, parens, em dashes, and ASCII alone so plain
///   prose passes through unchanged.
fn sanitize_scenario_for_markdown(raw: &str) -> String {
    let mut out = String::with_capacity(raw.len());
    for c in raw.chars() {
        match c {
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '[' => out.push_str("&#91;"),
            ']' => out.push_str("&#93;"),
            other => out.push(other),
        }
    }
    out
}

/// Flatten a macro's TokenStream into top-level arguments,
/// splitting on commas at the top level. Used for `skip_unless!`
/// where the body is an expression (typically a function call).
fn tokens_to_arg_list(tokens: proc_macro2::TokenStream) -> Vec<String> {
    let mut out: Vec<String> = Vec::new();
    let mut current = String::new();
    for tt in tokens {
        match &tt {
            proc_macro2::TokenTree::Punct(p)
                if p.as_char() == ',' && p.spacing() == proc_macro2::Spacing::Alone =>
            {
                out.push(current.trim().to_string());
                current.clear();
            }
            _ => {
                if !current.is_empty() && needs_space_before(&tt) {
                    current.push(' ');
                }
                current.push_str(&tt.to_string());
            }
        }
    }
    if !current.trim().is_empty() {
        out.push(current.trim().to_string());
    }
    out
}

fn needs_space_before(_tt: &proc_macro2::TokenTree) -> bool {
    // Conservative: never insert spaces. Tokens render with their
    // natural spacing via Display.
    false
}

// ---------------------------------------------------------------------------
// Markdown rendering
// ---------------------------------------------------------------------------

/// M4.3 flattened layout: every test gets its own subdirectory under
/// `.dot-agent-deck/recordings/`, holding the `.md` alongside the
/// cast and any failure artifacts. The catalog-area-to-milestone
/// inference of M4 is gone — future PRDs adding tests don't need to
/// pin a milestone subdir.
fn resolve_output_path(recordings_root: &Path, fn_name: &str) -> PathBuf {
    recordings_root.join(fn_name).join("test.md")
}

fn render_markdown(test: &DiscoveredTest, entry: &CatalogEntry, scenario: &str) -> String {
    let mut s = String::new();
    s.push_str(&format!("# {} — {}\n\n", entry.id, entry.headline));
    // PRD #83: derive the `<dir>/<file>` prefix from the source path
    // instead of hardcoding `tests/`, since `#[spec]` tests now also
    // live under `src/`.
    let src_file = test
        .source_path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("?");
    let src_dir = test
        .source_path
        .parent()
        .and_then(|p| p.file_name())
        .and_then(|n| n.to_str())
        .unwrap_or("tests");
    s.push_str(&format!(
        "**Source:** `{src_dir}/{src_file}::{}`\n",
        test.fn_name
    ));
    s.push_str(&format!("**Catalog:** {CATALOG_REF}\n"));
    let layer_is_l2 = entry
        .layer
        .as_deref()
        .map(|l| !l.to_lowercase().contains("l1"))
        .unwrap_or(true);
    if layer_is_l2 {
        s.push_str("**Cast:** `full-stream.cast`\n");
    }
    s.push('\n');

    s.push_str("## Scenario\n\n");
    s.push_str(&sanitize_scenario_for_markdown(scenario));
    s.push_str("\n\n");

    s.push_str("## Steps\n\n");
    if test.steps.is_empty() {
        s.push_str("_(no harness method calls recognised in this test body)_\n");
    } else {
        for (i, step) in test.steps.iter().enumerate() {
            s.push_str(&format!("{}. {step}\n", i + 1));
        }
    }
    s.push('\n');

    s.push_str("## Catalog spec\n\n");
    fn push_bullet(s: &mut String, label: &str, value: Option<&str>) {
        if let Some(v) = value {
            s.push_str(&format!("- **{label}:** {v}\n"));
        }
    }
    push_bullet(&mut s, "Layer", entry.layer.as_deref());
    push_bullet(&mut s, "Agent", entry.agent.as_deref());
    push_bullet(&mut s, "Asserts", entry.asserts.as_deref());
    push_bullet(&mut s, "Does not assert", entry.does_not_assert.as_deref());
    push_bullet(
        &mut s,
        "Platform coverage",
        entry.platform_coverage.as_deref(),
    );
    push_bullet(&mut s, "Cost note", entry.cost_note.as_deref());
    s.push('\n');

    if layer_is_l2 {
        s.push_str("## Replay\n\n```sh\n");
        // M4.3 flattened layout: cast lives next to this `.md`.
        s.push_str(&format!(
            "asciinema play .dot-agent-deck/recordings/{}/full-stream.cast\n",
            test.fn_name
        ));
        s.push_str("```\n\n");
    }

    s.push_str("## Rerun\n\n");
    let tier = if layer_is_l2 { "e2e" } else { "fast" };
    // Decision 17's `<sub>_<NNN>_…` prefix is unique by construction,
    // so we filter on `<sub>_<NNN>` which is shorter than the full
    // function name.
    let filter = sub_area_filter(&test.spec_id, &test.fn_name);
    s.push_str(&format!("```sh\ncargo test-{tier} {filter}\n```\n"));

    s
}

fn sub_area_filter(spec_id: &str, fn_name: &str) -> String {
    // Catalog IDs have shape `area/sub/NNN`; the Decision 17 prefix
    // is `<sub>_<NNN>` with `-` → `_` normalization. If we can't
    // derive that, fall back to the full fn name (still unique).
    if let Some((rest, nnn)) = spec_id.rsplit_once('/')
        && let Some((_, sub)) = rest.rsplit_once('/')
    {
        return format!("{}_{nnn}", sub.replace('-', "_"));
    }
    fn_name.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn doc_lines(raw: &[&str]) -> Vec<String> {
        raw.iter().map(|s| (*s).to_string()).collect()
    }

    #[test]
    fn scenario_extractor_accepts_singular_form() {
        let lines = doc_lines(&[" Scenario: launch the deck and assert"]);
        let out = extract_scenario_from_doc_lines(&lines).expect("scenario extracted");
        assert_eq!(out, "launch the deck and assert");
    }

    #[test]
    fn scenario_extractor_rejects_plural_form() {
        // M4.1 reviewer Nit 3 — the regex must not match
        // `/// Scenarios:` (plural). The whole doc block is just
        // a plural mention, so the extractor returns None.
        let lines = doc_lines(&[" Scenarios: the test covers two cases"]);
        assert!(extract_scenario_from_doc_lines(&lines).is_none());
    }

    #[test]
    fn scenario_extractor_preserves_paragraph_breaks() {
        // M4.1 reviewer S2 — a blank doc-comment line inside the
        // Scenario should become a `\n\n` paragraph break in the
        // rendered output, not silent truncation.
        let lines = doc_lines(&[
            " Scenario: first paragraph",
            " continues here.",
            "",
            " Second paragraph after a blank doc line.",
        ]);
        let out = extract_scenario_from_doc_lines(&lines).expect("scenario extracted");
        assert_eq!(
            out,
            "first paragraph continues here.\n\nSecond paragraph after a blank doc line."
        );
    }

    #[test]
    fn sanitize_scenario_escapes_html_and_link_brackets() {
        let raw = "click [here](javascript:alert(1)) and <script>boom</script>";
        let out = sanitize_scenario_for_markdown(raw);
        // Brackets escaped — no clickable markdown link possible.
        assert!(!out.contains('['));
        assert!(!out.contains(']'));
        // Angle brackets escaped — no raw HTML smuggling.
        assert!(!out.contains('<'));
        assert!(!out.contains('>'));
        // The literal text is still visible to a human reader.
        assert!(out.contains("javascript:alert(1)"));
        assert!(out.contains("script"));
    }

    #[test]
    fn sanitize_scenario_passes_plain_prose_unchanged() {
        // M4.1 stop-flag: spot-check that ordinary Scenario prose
        // — backticks, parentheses, em dashes, Unicode arrows —
        // is not mangled by the sanitizer.
        let raw =
            "Drive the agent through Thinking → Working → Idle. Card shows `Bash` during Working.";
        assert_eq!(sanitize_scenario_for_markdown(raw), raw);
    }

    #[test]
    fn inline_code_wraps_with_single_backtick_by_default() {
        assert_eq!(inline_code("Bash"), "`Bash`");
    }

    #[test]
    fn inline_code_escapes_internal_backticks() {
        // M4.1 auditor S6 — when the value already contains
        // backticks, pick a fence longer than the longest internal
        // run and pad with a single space on each side per
        // CommonMark inline-code rules.
        let out = inline_code("use `pwd`");
        assert_eq!(out, "`` use `pwd` ``");
    }

    #[test]
    fn inline_code_handles_multiple_backtick_runs() {
        let out = inline_code("a ` b `` c ``` d");
        // Longest run is 3, so the fence is 4 backticks.
        assert!(out.starts_with("```` "));
        assert!(out.ends_with(" ````"));
        assert!(out.contains("a ` b `` c ``` d"));
    }

    #[test]
    fn collect_spec_tests_from_items_discovers_both_top_level_and_nested() {
        // M4.6 P2: previously the discover_tests walker only scanned
        // `parsed.items` at the top level, so a #[spec] test placed
        // inside `#[cfg(test)] mod foo { ... }` was silently
        // dropped — and linkage-check rule 7 (which relies on the
        // same discovery) would let the missing test slide.
        let src = r#"
            #[spec("hooks/delivery/001")]
            #[test]
            /// Scenario: top-level fn.
            fn delivery_001_top() {}

            mod nested {
                #[spec("dashboard/pane/005")]
                #[test]
                /// Scenario: nested fn.
                fn pane_005_nested() {}

                mod deeper {
                    #[spec("chain-smoke/claude/002")]
                    #[test]
                    /// Scenario: doubly-nested fn.
                    fn claude_002_deep() {}
                }
            }
        "#;
        let parsed = syn::parse_file(src).expect("test src parses");
        let mut out: Vec<DiscoveredTest> = Vec::new();
        let dummy_path = std::path::PathBuf::from("tests/synthetic.rs");
        collect_spec_tests_from_items(&parsed.items, &dummy_path, &mut out);
        let ids: Vec<&str> = out.iter().map(|t| t.spec_id.as_str()).collect();
        assert!(ids.contains(&"hooks/delivery/001"));
        assert!(ids.contains(&"dashboard/pane/005"));
        assert!(
            ids.contains(&"chain-smoke/claude/002"),
            "doubly-nested mod should also be walked: {ids:?}"
        );
        assert_eq!(out.len(), 3);
    }
}
