//! The gh-aw `*.lock.yml` files are GENERATED, and Renovate edits them anyway.
//!
//! `gh aw compile` produces each lock from its `.md` source and records, in a
//! `gh-aw-manifest` comment at the top, the exact SHA and version of every
//! action the file pins. Renovate does not know the file is generated: it sees
//! `uses: …@<sha> # <version>` lines like any other workflow and bumps them,
//! leaving the rest of the generated content — and the manifest — behind.
//!
//! That is not hypothetical. On 2026-09-10, PR #989 bumped
//! `github/gh-aw-actions/setup` from v0.86.2 to v0.89.0 inside
//! `pr-review.lock.yml`. It rewrote all six `uses:` lines consistently — the
//! bump itself was not sloppy — but left the `gh-aw-manifest` comment, and the
//! action list comment beside it, recording v0.86.2. The v0.89.0 action was
//! then handed config generated by the v0.86.2 compiler, and every agent job
//! died with `Gateway configuration must specify exactly one of 'agentId' or
//! 'agentIds'`. The PR merged through Renovate's ruleset bypass, so nothing
//! stopped it, and the breakage surfaced only when someone ran the workflow.
//!
//! This is the same shape as `pin_lockstep.rs`: two places that must agree, in
//! files no single gate reads. The rules are mechanical — within one lock, every
//! pinned action must appear in that file's manifest at the same SHA, and no
//! action may appear at two SHAs. Nothing here says whether the pinned version
//! is *current*; that is Renovate's job.
//!
//! The remedy is to regenerate, not to hand-edit the pins into agreement: the
//! mismatch is a symptom, and the generated body is what actually has to change.
//! Either direction is valid — upgrade the `gh aw` CLI to the version Renovate
//! wants and recompile to ADOPT the bump, or recompile at the CLI version you
//! have to REVERT it (Renovate will then re-offer it, and this guard will hold
//! it for a human again, which is the same treatment issue #648 settled on for
//! the devbox/workflow toolchain pins).
//!
//! Two traps when regenerating, both hit while writing this:
//!
//! 1. **Compile per workflow, never bare.** `gh aw compile <name>` preserves
//!    `GH_AW_ACTION_FAILURE_ISSUE_EXPIRES_HOURS: "168"`; bare `gh aw compile`
//!    rewrites it to `"0"` in every lock. Same CLI, same sources — reproduced
//!    on v0.86.2. A bare recompile therefore smuggles a behaviour change into
//!    what looks like a pin-only diff.
//! 2. **The CLI version is not pinned by this repo.** Nothing in `devbox.json`
//!    or `scripts/` fixes it, so whoever recompiles decides which version the
//!    locks are generated at. Check `gh aw --version` first, and say which
//!    version you used in the commit.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("xtask/linkage-check sits two levels below the workspace root")
        .to_path_buf()
}

fn lock_files() -> Vec<PathBuf> {
    let dir = repo_root().join(".github/workflows");
    let mut out: Vec<PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.to_string_lossy().ends_with(".lock.yml"))
        .collect();
    out.sort();
    out
}

/// The `{repo: (sha, version)}` map the generator recorded in the file's own
/// `gh-aw-manifest` comment. That comment is a single JSON object on one line.
fn manifest_pins(text: &str) -> BTreeMap<String, (String, String)> {
    let mut pins = BTreeMap::new();
    // Scanned as text rather than parsed as JSON to keep this crate free of a
    // JSON dependency for one comment line; the shape is generator-controlled.
    let mut rest = text;
    while let Some(i) = rest.find("{\"repo\":\"") {
        rest = &rest[i..];
        let Some(end) = rest.find('}') else { break };
        let entry = &rest[..end];
        let field = |name: &str| -> Option<String> {
            let key = format!("\"{name}\":\"");
            let start = entry.find(&key)? + key.len();
            let tail = &entry[start..];
            Some(tail[..tail.find('"')?].to_string())
        };
        if let (Some(repo), Some(sha), Some(version)) =
            (field("repo"), field("sha"), field("version"))
        {
            pins.insert(repo, (sha, version));
        }
        rest = &rest[end..];
    }
    pins
}

/// Every `uses: <repo>@<sha> # <version>` in the file, with its line number.
fn used_pins(text: &str) -> Vec<(usize, String, String, String)> {
    let mut out = Vec::new();
    for (n, line) in text.lines().enumerate() {
        // Both YAML forms: a `uses:` key under a named step, and the bare
        // `- uses:` list item. The generated locks only use the first today,
        // but a parser that silently skips valid pins is the same class of
        // hole Greptile flagged in the manifest lookup, so accept both.
        let trimmed = line.trim();
        let trimmed = trimmed.strip_prefix("- ").unwrap_or(trimmed);
        let Some(after) = trimmed.strip_prefix("uses: ") else {
            continue;
        };
        let Some((reference, comment)) = after.split_once(" # ") else {
            continue;
        };
        let Some((repo, sha)) = reference.rsplit_once('@') else {
            continue;
        };
        if !sha.chars().all(|c| c.is_ascii_hexdigit()) || sha.len() < 40 {
            continue; // a tag or branch ref, not a pinned SHA
        }
        out.push((
            n + 1,
            repo.to_string(),
            sha.to_string(),
            comment.trim().to_string(),
        ));
    }
    out
}

fn short(sha: &str) -> &str {
    &sha[..8.min(sha.len())]
}

const REMEDY: &str = "Fix: regenerate with `gh aw compile <workflow-name>` (never bare — see the \
                      module docs) at the `gh aw` version you intend; do not hand-edit the pins \
                      into agreement, because the generated body has to change too.";

/// Every consistency problem in one lock file's text.
///
/// Pure over `(label, text)` so the synthetic tests below can exercise each
/// failure shape without a fixture on disk. Greptile's review of PR #996 asked
/// for exactly that: the file-walking test alone could pass vacuously, since
/// the real locks are (now) clean.
fn problems_in(label: &str, text: &str) -> Vec<String> {
    let manifest = manifest_pins(text);
    let pins = used_pins(text);

    if pins.is_empty() {
        return Vec::new(); // not a generated lock, or nothing pinned
    }
    if manifest.is_empty() {
        return vec![format!(
            "{label}: pins {} action(s) but has no gh-aw-manifest entries. Either this is not a \
             generated lock, or the manifest comment was stripped. {REMEDY}",
            pins.len()
        )];
    }

    let mut problems = Vec::new();
    let mut by_repo: BTreeMap<&str, BTreeMap<&str, Vec<usize>>> = BTreeMap::new();

    for (line, repo, sha, version) in &pins {
        by_repo
            .entry(repo)
            .or_default()
            .entry(sha)
            .or_default()
            .push(*line);

        match manifest.get(repo) {
            // The SHA decides which code runs, so it is what must agree. The
            // trailing comment is informational and its text varies — the
            // generator writes "v9.0.0 (source v9)" for some actions — so
            // comparing it would fail on files nothing has touched.
            Some((want_sha, want_version)) if sha != want_sha => problems.push(format!(
                "{label}:{line}: {repo} is pinned to {} (comment says {version}) but this file's \
                 own manifest records {} ({want_version}). Something edited this GENERATED file \
                 without regenerating it. {REMEDY}",
                short(sha),
                short(want_sha),
            )),
            Some(_) => {}
            // Greptile, PR #996: skipping this was a hole. A partial edit that
            // drops a manifest entry, or adds an action to the body only, would
            // otherwise pass a guard whose docs claim every pin is checked.
            None => problems.push(format!(
                "{label}:{line}: {repo} is pinned to {} but has NO entry in this file's \
                 gh-aw-manifest. Either the pin was added to the generated body by hand, or the \
                 manifest entry was removed. {REMEDY}",
                short(sha),
            )),
        }
    }

    for (repo, shas) in by_repo {
        if shas.len() > 1 {
            let detail: Vec<String> = shas
                .iter()
                .map(|(s, lines)| format!("{} at {lines:?}", short(s)))
                .collect();
            problems.push(format!(
                "{label}: {repo} is pinned at {} different SHAs — {}. That is a PARTIAL edit: \
                 something bumped some occurrences and missed others. {REMEDY}",
                shas.len(),
                detail.join(", "),
            ));
        }
    }

    problems
}

/// The real files must be internally consistent.
#[test]
fn generated_locks_agree_with_their_own_manifests() {
    let files = lock_files();
    assert!(
        !files.is_empty(),
        "no *.lock.yml found under .github/workflows — has the layout moved?"
    );

    let mut problems = Vec::new();
    for path in &files {
        let text = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
        problems.extend(problems_in(&path.display().to_string(), &text));
    }

    assert!(
        problems.is_empty(),
        "generated gh-aw lock files are inconsistent:\n  {}",
        problems.join("\n  ")
    );
}

/// Each failure shape, on constructed input. Without these the test above
/// passes whenever the real locks happen to be clean, which tells you nothing
/// about whether the check works.
#[cfg(test)]
mod synthetic {
    use super::problems_in;

    const SHA_A: &str = "6aab9e5b5c91c615506061f09bedd81a23babe3c";
    const SHA_B: &str = "af9516b9001c6aa6d4817b7484de4bb017ebb27f";

    fn lock(manifest_sha: &str, manifest_version: &str, uses: &[(&str, &str)]) -> String {
        let mut s = format!(
            "# gh-aw-manifest: {{\"version\":1,\"actions\":[{{\"repo\":\"github/gh-aw-actions/setup\",\"sha\":\"{manifest_sha}\",\"version\":\"{manifest_version}\"}}]}}\njobs:\n"
        );
        for (sha, version) in uses {
            s.push_str(&format!(
                "        uses: github/gh-aw-actions/setup@{sha} # {version}\n"
            ));
        }
        s
    }

    #[test]
    fn a_consistent_lock_has_no_problems() {
        let text = lock(SHA_A, "v0.86.2", &[(SHA_A, "v0.86.2"), (SHA_A, "v0.86.2")]);
        assert!(problems_in("t", &text).is_empty());
    }

    /// The #989 shape: every `uses:` bumped, manifest left behind.
    #[test]
    fn a_wholesale_bump_that_leaves_the_manifest_behind_is_caught() {
        let text = lock(SHA_A, "v0.86.2", &[(SHA_B, "v0.89.0"), (SHA_B, "v0.89.0")]);
        let p = problems_in("t", &text);
        assert_eq!(p.len(), 2, "one per pin: {p:?}");
        assert!(
            p.iter().all(|m| m.contains("own manifest records")),
            "{p:?}"
        );
    }

    /// The shape Greptile flagged: a pin with no manifest entry at all.
    #[test]
    fn a_pin_with_no_manifest_entry_is_caught() {
        let text = "# gh-aw-manifest: {\"version\":1,\"actions\":[{\"repo\":\"actions/checkout\",\"sha\":\"1111111111111111111111111111111111111111\",\"version\":\"v7\"}]}\njobs:\n        uses: github/gh-aw-actions/setup@6aab9e5b5c91c615506061f09bedd81a23babe3c # v0.86.2\n";
        let p = problems_in("t", text);
        assert_eq!(p.len(), 1, "{p:?}");
        assert!(
            p[0].contains("NO entry in this file's gh-aw-manifest"),
            "{}",
            p[0]
        );
    }

    /// A partial edit: some occurrences bumped, others missed.
    #[test]
    fn a_partial_bump_is_caught_as_two_shas() {
        let text = lock(SHA_B, "v0.89.0", &[(SHA_B, "v0.89.0"), (SHA_A, "v0.86.2")]);
        let p = problems_in("t", &text);
        assert!(
            p.iter().any(|m| m.contains("different SHAs")),
            "expected the partial-edit message: {p:?}"
        );
    }

    /// A stripped manifest must not read as "nothing to check".
    #[test]
    fn a_lock_with_pins_but_no_manifest_is_caught() {
        let text = format!("jobs:\n        uses: github/gh-aw-actions/setup@{SHA_A} # v0.86.2\n");
        let p = problems_in("t", &text);
        assert_eq!(p.len(), 1, "{p:?}");
        assert!(p[0].contains("no gh-aw-manifest entries"), "{}", p[0]);
    }

    /// The bare `- uses:` list form must parse too. The generated locks do not
    /// use it today, but a silent skip would hide a real pin if that changed.
    #[test]
    fn the_dash_uses_form_is_parsed() {
        let text = format!(
            "# gh-aw-manifest: {{\"repo\":\"github/gh-aw-actions/setup\",\"sha\":\"{SHA_A}\",\"version\":\"v0.86.2\"}}\njobs:\n      - uses: github/gh-aw-actions/setup@{SHA_B} # v0.89.0\n"
        );
        let p = problems_in("t", &text);
        assert_eq!(p.len(), 1, "the dash form was skipped entirely: {p:?}");
    }

    /// A file that pins nothing is not this guard's business.
    #[test]
    fn a_file_with_no_pins_is_ignored() {
        assert!(problems_in("t", "jobs:\n  build:\n    runs-on: ubuntu-latest\n").is_empty());
    }
}
