//! Issue #603: the adaptive issue labeler's post-agent memory validator.
//!
//! `.github/workflows/issue-labeler.md` hands an LLM a writable clone of the
//! `memory/issue-labeler` branch, then — in a `post-steps` job step that runs
//! after the agent and before anything is pushed — **recomputes** from the
//! triggering event and the structured classifier output exactly what that
//! clone is allowed to contain, and fails the step on any other difference.
//!
//! That step is the one part of the workflow's safety story that does not
//! depend on the model behaving. The safe-output allowlist bounds which labels
//! can be *applied*; nothing else bounds what the agent can *write into the
//! learning store*, which is read back into every later prompt. It shipped with
//! no test, which is what these tests exist to fix.
//!
//! They drive the **real** script under `node` against fixture memory trees
//! rather than a transcription of it, and cover both directions:
//!
//! - the two accepts the boundary must not block — a labeling-mode prediction,
//!   and a feedback record carrying more labels than a prediction may. The two
//!   caps differ deliberately (6 for a prediction, the whole taxonomy for a
//!   correction), so a test that only ever passes ≤6 labels would not notice
//!   them being collapsed into one.
//! - the rejects that are the reason the step exists: a row smuggled in for an
//!   unrelated issue, a row for another repository, a label outside the
//!   taxonomy, an extra file, feedback about an item the workflow never
//!   classified, and a feedback-mode run that tries to apply labels.
//!
//! **Why the script is extracted rather than vendored.** `*.lock.yml` is
//! generated by `gh aw compile` and the Markdown is the human-edited source, so
//! a copy of the script in this file would rot silently the first time either
//! moved. `issue_labeler_validator_lock_and_source_agree` closes the other half:
//! it asserts the extracted text is embedded verbatim in the generated lock,
//! which is what GitHub actually runs. Without it these tests could pass against
//! a source no runner ever sees.

use std::path::{Path, PathBuf};
use std::process::Command;

/// Human-edited agentic-workflow source. The heredoc below is extracted from
/// here, not from the lock, because this is the file a maintainer edits.
const WORKFLOW_MD: &str = ".github/workflows/issue-labeler.md";

/// `gh aw compile` output — the workflow GitHub actually runs.
const LOCK_YML: &str = ".github/workflows/issue-labeler.lock.yml";

/// The job step whose `run:` body is under test.
const STEP_NAME: &str = "Validate feedback memory";

/// Absolute paths the script hard-codes because a GitHub runner guarantees
/// them. A test cannot, so [`MemoryFixture::run`] redirects both into a
/// `TempDir` — and asserts each appears exactly once first, so renaming one in
/// the workflow fails loudly instead of quietly testing an unredirected path.
const MEMORY_ROOT_LITERAL: &str = "/tmp/gh-aw/repo-memory/default";
const AGENT_OUTPUT_LITERAL: &str = "/tmp/gh-aw/agent_output.json";

/// The validator derives its URL patterns from `GITHUB_REPOSITORY`, so the
/// fixtures have to agree with it on a slug.
const REPO_SLUG: &str = "vfarcic/dot-agent-deck";

/// Read a repository file with CRLF folded to LF.
///
/// The `build-windows` CI job runs this same tier, and nothing in
/// `.gitattributes` pins the line endings of these two files — so a checkout
/// that normalises to CRLF would otherwise defeat both the heredoc extraction
/// and the byte-comparison against the lock, on a platform where the failure
/// says nothing about the workflow.
fn read_lf(path: &Path) -> String {
    std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("{}: {e}", path.display()))
        .replace("\r\n", "\n")
}

/// Workspace root, from this crate's manifest dir rather than the process cwd,
/// so the tests do not depend on how the runner was invoked.
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("xtask/linkage-check sits two levels below the workspace root")
        .to_path_buf()
}

/// The runtime half needs `node`, which every GitHub runner and this repo's
/// devbox has. Where it is absent, say so loudly rather than failing a
/// contributor's unrelated change — the static half needs nothing.
fn node_present() -> bool {
    Command::new("node")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Pull the `Validate feedback memory` step's `node <<'SCRIPT' … SCRIPT`
/// heredoc out of the Markdown source and undo its six-space block indent.
fn validator_source() -> String {
    let md = read_lf(&repo_root().join(WORKFLOW_MD));
    let step = md
        .find(&format!("- name: {STEP_NAME}"))
        .unwrap_or_else(|| panic!("{WORKFLOW_MD}: no `{STEP_NAME}` step"));
    let open = "\n      node <<'SCRIPT'\n";
    let close = "\n      SCRIPT\n";
    let body_start = md[step..]
        .find(open)
        .map(|i| step + i + open.len())
        .unwrap_or_else(|| panic!("{WORKFLOW_MD}: `{STEP_NAME}` has no node heredoc"));
    let body_end = md[body_start..]
        .find(close)
        .map(|i| body_start + i)
        .unwrap_or_else(|| panic!("{WORKFLOW_MD}: `{STEP_NAME}` heredoc is unterminated"));
    md[body_start..body_end]
        .lines()
        .map(|l| l.strip_prefix("      ").unwrap_or(l))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Escape `s` the way a YAML double-quoted scalar does. The generated lock
/// emits the whole `run:` body as one such scalar, so this is what turns the
/// extracted heredoc back into the bytes to look for in it.
///
/// Only the three escapes this script actually needs are handled; anything else
/// that would need one panics rather than being silently mis-escaped into a
/// `contains` that can only fail.
fn yaml_double_quoted(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            c if c.is_ascii_graphic() || c == ' ' => out.push(c),
            c => panic!(
                "validator script contains {c:?}, which this escaper does not model — \
                 extend it and re-check the lock embedding"
            ),
        }
    }
    out.push('"');
    out
}

/// One run of the validator: a memory clone, the baseline snapshot taken before
/// the agent ran, the agent's structured output, and the triggering event.
struct MemoryFixture {
    /// Files in the writable memory clone — what the agent left behind.
    memory: Vec<(&'static str, String)>,
    /// Files in the pre-agent snapshot the validator diffs against.
    baseline: Vec<(&'static str, String)>,
    agent_output: String,
    event: String,
}

/// What `node` did with the fixture.
struct Outcome {
    accepted: bool,
    stderr: String,
}

impl Outcome {
    /// The validator reports every rejection by throwing, so the message is the
    /// only way to tell "rejected for the reason under test" from "rejected
    /// because the fixture was malformed".
    fn rejected_with(&self, needle: &str) -> bool {
        !self.accepted && self.stderr.contains(needle)
    }
}

impl MemoryFixture {
    /// Run the real script. `None` means the environment cannot run it at all.
    fn run(&self) -> Option<Outcome> {
        if !node_present() {
            eprintln!("SKIP: issue-labeler memory validator tests need `node` on PATH");
            return None;
        }

        let tmp = tempfile::tempdir().expect("tempdir");
        let memory = tmp.path().join("memory");
        let runner = tmp.path().join("runner");
        let baseline = runner.join("gh-aw").join("issue-labeler-memory-baseline");
        std::fs::create_dir_all(&memory).expect("memory dir");
        std::fs::create_dir_all(&baseline).expect("baseline dir");
        for (dir, files) in [(&memory, &self.memory), (&baseline, &self.baseline)] {
            for (name, contents) in files {
                std::fs::write(dir.join(name), contents).expect("fixture file");
            }
        }

        let agent_output = tmp.path().join("agent_output.json");
        let event = tmp.path().join("event.json");
        std::fs::write(&agent_output, &self.agent_output).expect("agent output");
        std::fs::write(&event, &self.event).expect("event");

        let script = redirect(
            &redirect(&validator_source(), MEMORY_ROOT_LITERAL, &memory),
            AGENT_OUTPUT_LITERAL,
            &agent_output,
        );
        let script_path = tmp.path().join("validate.js");
        std::fs::write(&script_path, script).expect("script");

        let out = Command::new("node")
            .arg(&script_path)
            .env("GITHUB_REPOSITORY", REPO_SLUG)
            .env("RUNNER_TEMP", &runner)
            .env("GITHUB_EVENT_PATH", &event)
            // Only read on the reusable-invocation path, where the event
            // payload carries no item; set so that path is exercisable.
            .env("ITEM_TYPE", "issue")
            .env("ITEM_NUMBER", "42")
            .output()
            .expect("node");
        Some(Outcome {
            accepted: out.status.success(),
            stderr: String::from_utf8_lossy(&out.stderr).into_owned(),
        })
    }
}

/// Replace a hard-coded runner path with a fixture one, insisting it occurred
/// exactly once. A silent miss would leave the script reading the real
/// `/tmp/gh-aw`, where an accept would prove nothing.
fn redirect(script: &str, literal: &str, replacement: &Path) -> String {
    let hits = script.matches(literal).count();
    assert_eq!(
        hits, 1,
        "expected exactly one `{literal}` in the validator, found {hits} — \
         the workflow moved it and these tests would no longer sandbox it"
    );
    // Both literals sit inside JS string literals. A Windows temp path is full
    // of backslashes, and an unescaped one is read as a JS escape — the `\r` of
    // a `...\runner\...` segment becomes a carriage return, not a separator.
    let replacement = replacement
        .to_str()
        .expect("utf-8 temp path")
        .replace('\\', "\\\\");
    script.replace(literal, &replacement)
}

fn issue_url(n: u32) -> String {
    format!("https://github.com/{REPO_SLUG}/issues/{n}")
}

/// A labeling-mode event: a freshly opened issue, no `label` key.
fn opened_issue_event(n: u32) -> String {
    format!(
        r#"{{"issue":{{"number":{n},"html_url":"{url}","title":"Deck panics on startup","body":"stack trace","labels":[]}}}}"#,
        url = issue_url(n)
    )
}

/// A feedback-mode event: a human changed `label` on an existing issue that
/// already carries `labels`.
fn label_changed_event(n: u32, changed: &str, labels: &[&str]) -> String {
    let labels = labels
        .iter()
        .map(|l| format!(r#"{{"name":"{l}"}}"#))
        .collect::<Vec<_>>()
        .join(",");
    format!(
        r#"{{"label":{{"name":"{changed}"}},"issue":{{"number":{n},"html_url":"{url}","title":"Deck panics on startup","body":"stack trace","labels":[{labels}]}}}}"#,
        url = issue_url(n)
    )
}

fn add_labels_output(labels: &[&str]) -> String {
    let labels = labels
        .iter()
        .map(|l| format!(r#""{l}""#))
        .collect::<Vec<_>>()
        .join(",");
    format!(r#"{{"items":[{{"type":"add_labels","labels":[{labels}]}}]}}"#)
}

const NOOP_OUTPUT: &str = r#"{"items":[{"type":"noop"}]}"#;

fn prediction(n: u32, labels: &[&str]) -> String {
    let labels = labels
        .iter()
        .map(|l| format!(r#""{l}""#))
        .collect::<Vec<_>>()
        .join(",");
    format!(
        r#"{{"url":"{url}","type":"issue","labels":[{labels}]}}"#,
        url = issue_url(n)
    )
}

fn feedback(n: u32, labels: &[&str]) -> String {
    let labels = labels
        .iter()
        .map(|l| format!(r#""{l}""#))
        .collect::<Vec<_>>()
        .join(",");
    format!(
        r#"{{"url":"{url}","content":"Deck panics on startup\nstack trace","labels":[{labels}]}}"#,
        url = issue_url(n)
    )
}

// ---------------------------------------------------------------------------
// Static: the tested script is the shipped script
// ---------------------------------------------------------------------------

/// The Markdown is what a maintainer edits; the lock is what GitHub runs, and
/// `gh aw compile` is the only thing that keeps them in step. If the two drift
/// — an edit landed without a recompile — every runtime test below would go on
/// passing against a script no runner ever executes, so this is the assertion
/// that gives the others their meaning.
#[test]
fn issue_labeler_validator_lock_and_source_agree() {
    let embedded = yaml_double_quoted(&format!("node <<'SCRIPT'\n{}\nSCRIPT", validator_source()));
    let lock = read_lf(&repo_root().join(LOCK_YML));
    assert!(
        lock.contains(&embedded),
        "the `{STEP_NAME}` script in {WORKFLOW_MD} is not embedded verbatim in {LOCK_YML} — \
         recompile with `gh aw compile issue-labeler issue-labeler-preview --validate --strict --approve`"
    );
}

/// Slice out the text between `open` and the next `close`, insisting `open`
/// occurs exactly once so an anchor the workflow moved fails loudly instead of
/// silently matching somewhere else.
fn between<'a>(haystack: &'a str, open: &str, close: &str) -> &'a str {
    let hits = haystack.matches(open).count();
    assert_eq!(hits, 1, "expected exactly one `{open}`, found {hits}");
    let start = haystack.find(open).expect("checked above") + open.len();
    let len = haystack[start..]
        .find(close)
        .unwrap_or_else(|| panic!("no `{close}` after `{open}`"));
    &haystack[start..start + len]
}

/// Split a `["a", "b"]`-shaped list into its literal members.
fn quoted_list(inner: &str) -> Vec<String> {
    inner
        .split(',')
        .map(|item| item.trim().trim_matches('"').to_string())
        .filter(|item| !item.is_empty())
        .collect()
}

/// The safe-output allowlist bounds what may be **applied**; the validator
/// carries a second, independent copy of the same policy bounding what may be
/// **stored**. Nothing but this keeps the two in step, and they have already
/// drifted once: PR #739 moved `add-labels.max` 5 → 6 and added three component
/// labels to the allowlist while the validator kept both old values, so the
/// sixth label the change existed to permit would have been applied and then
/// rejected by the post-step — failing the run instead of persisting the
/// prediction.
///
/// The correction cap is deliberately *not* checked against `max`: a feedback
/// record snapshots whatever a maintainer left on the item, so it is bounded by
/// the whole taxonomy (`allowedLabels.size`) rather than by what the classifier
/// may propose. `issue_labeler_accepts_seven_label_feedback` covers that side.
#[test]
fn issue_labeler_validator_policy_matches_the_frontmatter() {
    let md = read_lf(&repo_root().join(WORKFLOW_MD));
    let script = validator_source();

    let declared_max = between(&md, "\n  add-labels:\n    max: ", "\n").trim();
    let enforced_max = between(&script, "const maxPredictionLabels = ", ";").trim();
    assert_eq!(
        declared_max, enforced_max,
        "{WORKFLOW_MD}: `add-labels.max` is {declared_max} but the memory validator caps a \
         prediction at {enforced_max} — the extra label would be applied and then rejected"
    );

    let declared = quoted_list(between(&md, "\n    allowed: [\"", "]\n"));
    let enforced = quoted_list(between(&script, "const allowedLabels = new Set([\"", "]);"));
    assert!(
        !declared.iter().any(|l| l.contains('*') || l.contains('?')),
        "{WORKFLOW_MD}: the allowlist gained a glob, which the validator's literal set cannot \
         mirror — teach it the pattern before widening this check"
    );
    assert_eq!(
        declared, enforced,
        "{WORKFLOW_MD}: the safe-output allowlist and the memory validator disagree on the \
         taxonomy — a label the workflow may apply cannot be stored as a learned example"
    );
}

// ---------------------------------------------------------------------------
// Accept: what the boundary must let through
// ---------------------------------------------------------------------------

/// Labeling mode on a fresh issue: the agent appends exactly the prediction its
/// own structured output implies, to a store that was empty. The base case —
/// if this rejects, the workflow cannot learn at all.
#[test]
fn issue_labeler_records_a_valid_prediction() {
    let fixture = MemoryFixture {
        memory: vec![(
            "predictions.jsonl",
            format!(
                "{}\n",
                prediction(42, &["bug", "priority:high", "size:low"])
            ),
        )],
        baseline: vec![],
        agent_output: add_labels_output(&["priority:high", "bug", "size:low"]),
        event: opened_issue_event(42),
    };
    let Some(out) = fixture.run() else { return };
    assert!(
        out.accepted,
        "a prediction matching the classifier output was rejected:\n{}",
        out.stderr
    );
}

/// Feedback mode, and the case that pins the two caps apart. A **prediction**
/// may carry at most 6 labels; a maintainer's correction snapshots whatever the
/// item now has, which can legitimately exceed that. Seven selectable labels is
/// therefore a shape only the feedback path may accept — and the event also
/// carries the blocked `PRD` label, which must be filtered back out rather than
/// stored.
#[test]
fn issue_labeler_accepts_seven_label_feedback() {
    let corrected = [
        "bug",
        "config",
        "daemon",
        "priority:high",
        "size:medium",
        "source",
        "tests",
    ];
    let mut event_labels = corrected.to_vec();
    event_labels.push("PRD");
    let classified = format!("{}\n", prediction(42, &["bug"]));
    let fixture = MemoryFixture {
        memory: vec![
            ("predictions.jsonl", classified.clone()),
            (
                "feedback-issue.jsonl",
                format!("{}\n", feedback(42, &corrected)),
            ),
        ],
        baseline: vec![("predictions.jsonl", classified)],
        agent_output: NOOP_OUTPUT.to_string(),
        event: label_changed_event(42, "size:medium", &event_labels),
    };
    let Some(out) = fixture.run() else { return };
    assert!(
        out.accepted,
        "a seven-label correction was rejected — the prediction cap has leaked onto the \
         feedback path, and every larger correction is now unlearnable:\n{}",
        out.stderr
    );
}

// ---------------------------------------------------------------------------
// Reject: what the boundary exists to stop
// ---------------------------------------------------------------------------

/// The headline case. The store is read back into later prompts, so a row the
/// agent invents for an issue the run never touched is a durable, self-authored
/// instruction to itself. The prediction it *was* asked for is present and
/// correct; only the extra row is unaccounted for.
#[test]
fn issue_labeler_rejects_a_smuggled_prediction() {
    let fixture = MemoryFixture {
        memory: vec![(
            "predictions.jsonl",
            format!(
                "{}\n{}\n",
                prediction(42, &["bug", "priority:high", "size:low"]),
                prediction(9001, &["priority:low"]),
            ),
        )],
        baseline: vec![],
        agent_output: add_labels_output(&["bug", "priority:high", "size:low"]),
        event: opened_issue_event(42),
    };
    let Some(out) = fixture.run() else { return };
    assert!(
        out.rejected_with("changes do not match the triggering event"),
        "a row for an untouched issue was accepted:\n{}",
        out.stderr
    );
}

/// Same shape from the other side: the row is for *this* run's event but points
/// at another repository, which is how a poisoned store would reference content
/// the maintainers cannot see.
#[test]
fn issue_labeler_rejects_a_foreign_repository_url() {
    let fixture = MemoryFixture {
        memory: vec![(
            "predictions.jsonl",
            "{\"url\":\"https://github.com/attacker/evil/issues/42\",\"type\":\"issue\",\
             \"labels\":[\"bug\"]}\n"
                .to_string(),
        )],
        baseline: vec![],
        agent_output: add_labels_output(&["bug"]),
        event: opened_issue_event(42),
    };
    let Some(out) = fixture.run() else { return };
    assert!(
        out.rejected_with("invalid prediction entry"),
        "a prediction pointing outside {REPO_SLUG} was accepted:\n{}",
        out.stderr
    );
}

/// The taxonomy is enforced on the *memory* as well as on the labels applied.
/// `PRD` is on the safe-output blocklist, so it can never be applied — storing
/// it as a learned example would teach the model to keep proposing it.
#[test]
fn issue_labeler_rejects_a_non_taxonomy_label() {
    let fixture = MemoryFixture {
        memory: vec![(
            "predictions.jsonl",
            format!("{}\n", prediction(42, &["PRD"])),
        )],
        baseline: vec![],
        agent_output: add_labels_output(&["PRD"]),
        event: opened_issue_event(42),
    };
    let Some(out) = fixture.run() else { return };
    assert!(
        out.rejected_with("invalid labels"),
        "a blocked label was stored as a learned example:\n{}",
        out.stderr
    );
}

/// A prediction may name at most 6 labels. Paired with the seven-label feedback
/// test above, this is what holds the two caps apart in both directions.
#[test]
fn issue_labeler_rejects_an_oversized_prediction() {
    let seven = [
        "bug",
        "config",
        "daemon",
        "priority:high",
        "size:low",
        "source",
        "tests",
    ];
    let fixture = MemoryFixture {
        memory: vec![("predictions.jsonl", format!("{}\n", prediction(42, &seven)))],
        baseline: vec![],
        agent_output: add_labels_output(&seven),
        event: opened_issue_event(42),
    };
    let Some(out) = fixture.run() else { return };
    assert!(
        out.rejected_with("invalid labels"),
        "a 7-label prediction was accepted past the documented cap of 6:\n{}",
        out.stderr
    );
}

/// The memory clone is a git worktree the agent can write anywhere in. Only the
/// three `.jsonl` stores may exist in it, so an extra file — the natural shape
/// of an exfiltration or of a second, unvalidated store — fails the step.
#[test]
fn issue_labeler_rejects_an_unexpected_memory_file() {
    let fixture = MemoryFixture {
        memory: vec![
            (
                "predictions.jsonl",
                format!("{}\n", prediction(42, &["bug"])),
            ),
            ("notes.txt", "harvested\n".to_string()),
        ],
        baseline: vec![],
        agent_output: add_labels_output(&["bug"]),
        event: opened_issue_event(42),
    };
    let Some(out) = fixture.run() else { return };
    assert!(
        out.rejected_with("unexpected memory entry: notes.txt"),
        "an extra file in the memory clone was accepted:\n{}",
        out.stderr
    );
}

/// Feedback is only ground truth about a prediction the workflow actually made.
/// A correction recorded for an item it never classified is an unlabelled
/// example the model wrote for itself, so the validator requires the item to be
/// present in the pre-agent `predictions.jsonl`.
#[test]
fn issue_labeler_rejects_feedback_for_an_unclassified_item() {
    let fixture = MemoryFixture {
        memory: vec![(
            "feedback-issue.jsonl",
            format!("{}\n", feedback(42, &["bug"])),
        )],
        baseline: vec![],
        agent_output: NOOP_OUTPUT.to_string(),
        event: label_changed_event(42, "bug", &["bug"]),
    };
    let Some(out) = fixture.run() else { return };
    assert!(
        out.rejected_with("changes do not match the triggering event"),
        "feedback was stored for an item the workflow never classified:\n{}",
        out.stderr
    );
}

/// Feedback mode reacts to a human's label change, so it must never turn around
/// and apply labels of its own — that would let one maintainer edit trigger an
/// unbounded relabel, and each relabel is itself a `labeled` event.
#[test]
fn issue_labeler_rejects_labels_applied_in_feedback_mode() {
    let classified = format!("{}\n", prediction(42, &["bug"]));
    let fixture = MemoryFixture {
        memory: vec![("predictions.jsonl", classified.clone())],
        baseline: vec![("predictions.jsonl", classified)],
        agent_output: add_labels_output(&["priority:high"]),
        event: label_changed_event(42, "bug", &["bug"]),
    };
    let Some(out) = fixture.run() else { return };
    assert!(
        out.rejected_with("feedback mode must finish with noop"),
        "a feedback-mode run was allowed to apply labels:\n{}",
        out.stderr
    );
}
