pub mod agent_pty;
pub mod agent_registry;
pub mod ascii_art;
pub mod build_id;
pub mod build_version_handshake;
pub mod codex_hooks_manage;
pub mod config;
pub mod config_gen;
pub mod config_validation;
pub mod connect;
pub mod daemon;
pub mod daemon_attach;
pub mod daemon_client;
pub mod daemon_protocol;
pub mod daemon_status;
pub mod daemon_stop;
pub mod devin_hooks_manage;
pub mod dispatch;
pub mod embedded_pane;
pub mod error;
pub mod event;
pub mod features;
pub mod hook;
pub mod hooks_manage;
pub mod hyperlink;
pub mod init;
pub mod issue_dispatch;
pub mod issue_dispatch_run;
pub mod keybindings;
pub mod llm;
pub mod login_shell;
pub mod mode_manager;
pub mod opencode_manage;
pub mod orchestrator_context;
pub mod orchestrator_ext;
pub mod palette;
pub mod pane;
pub mod pane_input;
pub mod platform;
pub mod project_config;
pub mod remote;
pub mod schedule_cli;
pub mod scheduler;
pub mod spawn;
pub mod state;
pub mod tab;
pub mod tab_layout;
pub mod terminal_widget;
// Issue #322: test-only, and never part of the shipped library. Unit tests in
// this crate do not link `tests/common/`, so before this they allocated scratch
// space in the OS temp dir — the RAM-backed `/tmp` the issue is about.
#[cfg(test)]
mod test_temp;
pub mod ui;
pub mod version;
pub mod watch;
pub mod worktree_reclaim;
pub mod wrap;
